name: Puller2 CI/CD

env:
  APP: "puller2"
  HOST_PORT: 5001
  CONTAINER_PORT: 5000
  LATEST_TAG: latest
  NUMBERED_TAG: v0.0.${{ NUMBERED_TAG_PREFIX }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.APP }}:${{ env.LATEST_TAG }}
          ${{ secrets.DOCKER_USERNAME }}/${{ env.APP }}:${{ env.NUMBERED_TAG }}
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Localstack
      run: |
        echo "I AM HERE 2"
#        docker run --rm -d -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} ${{ secrets.DOCKER_USERNAME }}/${{ steps.string.outputs.lowercase }}:${{ env.TAG }}
